### ISSUE TITLE
Add "draft" flag to unfinished mini stories so they don't build

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#157]
Instead of merging lots of PRs to a dev branch while a new mini is in development, let's set this repo up so that any folder with a "draft" flag does not get built. This way we can merge new PRs to main without getting a dev branch wildly out of sync from main.

When a story is ready to deploy, we can remove the "draft" flag.

- [x] Set up template so all new stories have the draft flag.
- [x] Add draft flag to all unfinished stories (RadWave & AnnularEclipse)

**Comment by Carifio24** [comment]
#146 now has some functionality to only deploy non-draft stories (and the template sets up new stories to have `draft: true` in the `package.json`). It seems to run fine in my local testing but I'm not sure whether we can test it on here without merging it in.
