### ISSUE TITLE
Minor css issue for bottom CosmicDS icon

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#179]
This issue appeared in #175, but I went ahead and merged it, so we still have to fix it.

If you hide and reopen the top content (with the map), a gray overlay appears on top of the CosmicDS logo.

<img width="1644" alt="Screen Shot 2023-09-19 at 7 06 21 PM" src="https://github.com/cosmicds/minids/assets/12750048/a8fcf187-c942-4682-a07c-d74a078dee89">

**Comment by johnarban** [comment]
This issue is that when double-clicking to select on a page, the browser selects _something according to some rule_. In https://github.com/cosmicds/minids/pull/178/commits/e7b62b6ea9a8d8566be92e42c6f4448a0233d1c5 on #178 I disable `user-select` to prevent clicking near the buttons.
