### ISSUE TITLE
Only run CI for packages that (might) be affected by a change

### ISSUE THREAD

**Issue by Carifio24** [cosmicds/minids#221]
It would be nice to only need to re-run the PR CI for workspaces that have actually changed. (The exception would be common, since a change there could potentially touch every other story workspace). Maybe we can use [this](https://github.com/igrek8/yarn-changed-workspaces) to help facilitate that?

We probably want to re-run the full CI on a merge to master - I'm thinking that this change would be for PRs only.

**Comment by johnarban** [comment]
Yes! Pat and I were just talking about this. This would be great since everything only needs to be checked if common is changed.

**Comment by Carifio24** [comment]
Now that we've split all of these stories into their own repositories, this is no longer a problem.
