### ISSUE TITLE
Brick Mini UI issue

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#293]
Dropping this here, so I don't forget about it while we're away this week.

When the bottom slider is moved toward Spitzer/GLIMPSE, the top slider automatically goes to the no-stars Brick instead of staying on the stars Brick.

**Comment by johnarban** [comment]
I am not seeing this issue on main, or at least I am not noticing anything unexpected. There is an issue in that it initializes to 50% opacity but the sliders are all at 100%
