### ISSUE TITLE
Finish Brick Mini before Monday 12/4.

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#301]
- [x] @johnarban, please reduce file size for video I posted on the slack thread (`BrickMiniDSVideo3.mp4`) and add to the Mini.
- [x] If possible, it might be good if @heywooddogwood, @johnarban, or @Carifio24  could take a look at placing this figure in the in text a little more gracefully than I did. 
<img width="854" alt="Screen Shot 2023-12-02 at 12 31 20 AM" src="https://github.com/cosmicds/minids/assets/12750048/3bb5252d-d000-4dfc-b72f-890f0846e13b">

**Comment by johnarban** [comment]
formatted the diagram to like this on narrow
<img width="446" alt="image" src="https://github.com/cosmicds/minids/assets/7862929/5c63ab4f-3e42-469c-be32-b4303970fc41">

and this on wide. It will take up no more than 50% of the width. 
<img width="699" alt="image" src="https://github.com/cosmicds/minids/assets/7862929/ed3ec831-f9bf-4d35-b66b-4aed9c8f7797">
